version: "3.10"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
  redis:
    image: redis:latest
    container_name: redis
  app:
    container_name: app_fastapi
    build:
      context: .
      dockerfile: app_fastapi/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - redis
    depends_on:
      - redis
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: main/Dockerfile
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
  db:
    image: postgres:latest
    container_name: db
    command: -p 5432
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER:?err}
      - POSTGRES_PASSWORD=${DB_PASS:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data